name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # 指定 GitHub 运行环境
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 连接服务器并部署
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.HUAWEI_CLOUD }}
          script: |
            cd ../myToDo/myToDo  # 切换到项目目录
            git pull origin main      # 拉取最新代码
            nohup pnpm dev &   # 启动前端服务
            cd server
            nohup go run main.go &  # 启动后端服务
            
