name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # 指定 GitHub 运行环境
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 连接服务器并部署
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "60.204.240.235"
          username: "root"
          key: ${{ secrets.HUAWEI_CLOUD }}
          port: 22
          script: |
            echo "当前主机名：" $(hostname)  # 确保连接的是你的服务器
            echo "当前用户：" $(whoami)
            echo "当前目录：" $(pwd)
            cd ../myToDo/myToDo  # 切换到项目目录
            git pull origin main      # 拉取最新代码
            pnpm build    # 启动前端服务
            sudo cp -r dist/* /var/www/html/new_project/
            cd server
            echo "当前目录：" $(pwd)
            go build -o myserver main.go   # 启动后端服务
            # pkill -f myserver || true  # 杀死之前的进程，避免端口占用
            # echo "当前目录：" $(pwd)
            # nohup ./myserver & # 让服务后台运行


            
